version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rzmjxfme3jrw"
s3_prefix = "wello"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
