version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::866503935015:user/ktingyew_sam"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::866503935015:role/GitHubActionsRole"
cloudformation_execution_role = "arn:aws:iam::866503935015:role/CloudFormationCustomRole"
artifacts_bucket = "myartifactsbucketforsam"
image_repository = ""
region = "ap-southeast-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::866503935015:role/GitHubActionsRole"
cloudformation_execution_role = "arn:aws:iam::866503935015:role/CloudFormationCustomRole"
artifacts_bucket = "myartifactsbucketforsam"
image_repository = ""
region = "ap-southeast-1"
